import React, { useMemo } from "react";
import { Radio, CalendarDays, MapPin, Tv } from "lucide-react";
import { FaChessKnight, FaBasketballBall, FaFutbol, FaCar, FaPuzzlePiece, FaCrown, FaGamepad, FaCrosshairs } from "react-icons/fa";
import myBackground from "../images/mybackground4.jpg";
import { useNotifications } from "../context/NotificationContext";

export default function Games(){
 const {scheduleGames}=useNotifications();
 const grouped=useMemo(()=>({live:scheduleGames.filter(g=>g.status==="live"),upcoming:scheduleGames.filter(g=>g.status==="upcoming"),completed:scheduleGames.filter(g=>g.status==="completed")}),[scheduleGames]);
 const games=[
 {title:"Chess",description:"Challenge your mind with classic chess.",icon:<FaChessKnight size={40} className="text-amber-400"/>,link:"https://www.chess.com/play"},
 {title:"Basketball Legends",description:"Play exciting online basketball matches.",icon:<FaBasketballBall size={40} className="text-orange-500"/>,link:"https://www.crazygames.com/game/basketball-legends"},
 {title:"Football Soccer",description:"Kick off fun soccer matches online.",icon:<FaFutbol size={40} className="text-green-500"/>,link:"https://www.miniclip.com/games/soccer-stars/"},
 {title:"Car Racing",description:"Speed through thrilling race tracks.",icon:<FaCar size={40} className="text-red-500"/>,link:"https://www.crazygames.com/t/car"},
 {title:"Block Puzzle",description:"Relax with addictive block puzzles.",icon:<FaPuzzlePiece size={40} className="text-blue-500"/>,link:"https://www.blockpuzzle.com/"},
 {title:"Royal Match",description:"Match colorful tiles in royal style.",icon:<FaCrown size={40} className="text-yellow-400"/>,link:"https://play.google.com/store/apps/details?id=com.dreamgames.royalmatch"},
 {title:"Arcade Games",description:"Classic arcade fun at your fingertips.",icon:<FaGamepad size={40} className="text-purple-500"/>,link:"https://www.crazygames.com/t/arcade"},
 {title:"Pool",description:"Classic 8-ball pool online.",icon:<FaGamepad size={40} className="text-teal-400"/>,link:"https://www.miniclip.com/games/8-ball-pool/"},
 {title:"Zuma Marble Blast",description:"Shoot marbles to clear the path.",icon:<FaPuzzlePiece size={40} className="text-pink-500"/>,link:"https://www.crazygames.com/game/zuma"},
 {title:"Call of Duty",description:"Legendary FPS action game.",icon:<FaCrosshairs size={40} className="text-gray-300"/>,link:"https://www.callofduty.com/play"},
 {title:"Purge",description:"Survive intense shooting battles.",icon:<FaCrosshairs size={40} className="text-red-600"/>,link:"https://www.crazygames.com/game/purge"},
 ];
 return <div className="min-h-screen text-gray-100 py-12 px-4 sm:px-6 bg-cover bg-center bg-fixed" style={{backgroundImage:`linear-gradient(rgba(0,0,0,.58),rgba(0,0,0,.64)),url(${myBackground})`}}><div className="max-w-7xl mx-auto">
 <section className="mb-16"><div className="text-center mb-8"><p className="text-orange-400 text-xs font-black uppercase tracking-[.35em]">Synced directly from Schedule</p><h1 className="text-4xl sm:text-5xl font-black uppercase mt-2">J-Town Game <span className="text-orange-500">Roster</span></h1><p className="text-neutral-400 mt-3">Every live, upcoming and completed basketball game is pulled from the same master schedule.</p></div>
 <div className="grid lg:grid-cols-3 gap-6"><GameColumn title="Live Now" icon={<Radio size={18}/>} games={grouped.live} empty="No live game right now."/><GameColumn title="Upcoming" icon={<CalendarDays size={18}/>} games={grouped.upcoming} empty="No upcoming games."/><GameColumn title="Completed" icon={<FaBasketballBall/>} games={grouped.completed} empty="No completed games yet."/></div></section>
 <section className="border-t border-neutral-800 pt-12"><h2 className="text-4xl font-extrabold text-center text-amber-500 uppercase tracking-widest mb-3 animate-pulse">Games Portal</h2><p className="text-center text-gray-400 mb-12">Explore and play exciting games online. Works on mobile and laptops!</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">{games.map((game,idx)=><a key={idx} href={game.link} target="_blank" rel="noopener noreferrer" className="group bg-[#141412] rounded-xl overflow-hidden shadow-lg border border-neutral-800 hover:border-amber-500/40 transition-all transform hover:-translate-y-2 hover:shadow-amber-500/20 p-6 flex flex-col items-center text-center"><div className="mb-4 group-hover:scale-110 transition-transform duration-500">{game.icon}</div><h3 className="text-xl font-bold text-white group-hover:text-amber-400 transition-colors">{game.title}</h3><p className="text-sm text-gray-400 mt-2">{game.description}</p><span className="mt-5 text-xs uppercase font-black tracking-wider text-amber-400">Play now →</span></a>)}</div></section>
 </div></div>
}
function GameColumn({title,icon,games,empty}){return <div className="bg-black/60 border border-neutral-800 rounded-2xl p-4"><h2 className="font-black uppercase flex items-center gap-2 mb-4 text-orange-400">{icon}{title}<span className="ml-auto text-xs bg-neutral-900 px-2 py-1 rounded-full text-neutral-400">{games.length}</span></h2><div className="space-y-3">{games.length?games.map(g=><div key={g.id} className="bg-[#141412] border border-neutral-800 rounded-xl p-4"><p className="text-[10px] uppercase text-orange-400 font-black">{g.gameType}</p><div className="flex items-center justify-between gap-3 my-3"><div className="flex-1 text-center"><img src={g.homeLogo} className="w-11 h-11 rounded-full object-cover mx-auto"/><p className="text-xs font-bold mt-1">{g.homeTeam}</p></div><div className="text-center">{g.homeScore!==null&&g.awayScore!==null?<p className="text-xl font-black">{g.homeScore}:{g.awayScore}</p>:<p className="font-black text-orange-400">VS</p>}<p className="text-[10px] text-neutral-500">{g.time}</p></div><div className="flex-1 text-center"><img src={g.awayLogo} className="w-11 h-11 rounded-full object-cover mx-auto"/><p className="text-xs font-bold mt-1">{g.awayTeam}</p></div></div><div className="text-[11px] text-neutral-500 border-t border-neutral-800 pt-3 space-y-1"><p className="flex gap-2"><CalendarDays size={13}/>{g.date}</p><p className="flex gap-2"><MapPin size={13}/>{g.venue}</p><p className="flex gap-2"><Tv size={13}/>{g.broadcast}</p></div></div>):<div className="border border-dashed border-neutral-800 rounded-xl p-6 text-center text-neutral-600 text-sm">{empty}</div>}</div></div>}
