import { useState } from "react";
import { Newspaper, Plus, Pencil, Trash2, X, Save } from "lucide-react";
import myBackground from "../images/mybackground4.jpg";
import { useNotifications } from "../context/NotificationContext";
import { useAuth } from "../context/AuthContext";
const blank={title:"",desc:"",category:"general",link:"/news"};
export default function News(){
 const {newsFeed,addNews,updateNews,removeNews}=useNotifications(); const {isAdmin}=useAuth();
 const [open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank);
 const startAdd=()=>{setEditing(null);setForm(blank);setOpen(true)};
 const startEdit=(a)=>{setEditing(a.id);setForm({title:a.title||"",desc:a.desc||"",category:a.category||"general",link:a.link||"/news"});setOpen(true)};
 const save=(e)=>{e.preventDefault();if(!form.title.trim())return; editing?updateNews(editing,form):addNews(form);setOpen(false)};
 return <div className="min-h-screen text-white px-4 sm:px-6 py-10 bg-cover bg-center bg-fixed" style={{backgroundImage:`linear-gradient(rgba(0,0,0,.58),rgba(0,0,0,.65)),url(${myBackground})`}}><div className="max-w-5xl mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-8"><div><p className="text-orange-400 text-xs font-black uppercase tracking-[.35em]">J-Town Media Centre</p><h1 className="text-4xl sm:text-5xl font-black mt-2 flex gap-3 items-center"><Newspaper className="text-orange-500"/> News Feed</h1><p className="text-neutral-400 mt-2">Official stories, roster changes and league updates.</p></div>{isAdmin&&<button onClick={startAdd} className="bg-orange-500 hover:bg-orange-400 text-black font-black px-5 py-3 rounded-xl flex gap-2 items-center justify-center"><Plus size={18}/> Publish News</button>}</div>
  <div className="space-y-4">{newsFeed.map(a=><article key={a.id} className="bg-black/75 border border-neutral-800 hover:border-orange-500/50 rounded-2xl p-6"><div className="flex gap-4"><div className="p-3 h-fit bg-orange-500/10 rounded-xl"><Newspaper className="text-orange-400"/></div><div className="flex-1"><div className="flex flex-wrap justify-between gap-2"><div><span className="text-[10px] uppercase tracking-widest text-orange-400 font-black">{a.category}</span><h2 className="text-xl font-black mt-1">{a.title}</h2></div><span className="text-xs text-neutral-500">{a.date}</span></div><p className="text-neutral-300 mt-3 leading-relaxed">{a.desc}</p>{isAdmin&&<div className="flex gap-2 mt-4"><button onClick={()=>startEdit(a)} className="px-3 py-2 rounded-lg bg-orange-500/10 text-orange-400 flex gap-2"><Pencil size={15}/> Edit</button><button onClick={()=>window.confirm(`Delete ${a.title}?`)&&removeNews(a.id)} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400 flex gap-2"><Trash2 size={15}/> Delete</button></div>}</div></div></article>)}</div>
 </div>{open&&isAdmin&&<div className="fixed inset-0 z-[12000] bg-black/85 backdrop-blur-sm p-4 flex items-center justify-center"><form onSubmit={save} className="w-full max-w-2xl bg-[#111] border border-neutral-800 rounded-3xl p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{editing?"Edit News":"Publish News"}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="space-y-4 mt-5"><Field label="Headline" value={form.title} set={v=>setForm({...form,title:v})}/><label className="text-sm text-neutral-400">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-800 rounded-xl p-3 text-white"><option>general</option><option>games</option><option>schedule</option><option>players</option><option>teams</option></select></label><label className="text-sm text-neutral-400">Story<textarea rows="6" value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-800 rounded-xl p-3 text-white"/></label></div><button className="mt-5 w-full bg-orange-500 text-black font-black py-3 rounded-xl flex gap-2 justify-center"><Save size={17}/> Save News</button></form></div>}</div>
}
function Field({label,value,set}){return <label className="text-sm text-neutral-400">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full bg-neutral-950 border border-neutral-800 rounded-xl p-3 text-white"/></label>}
