import { useMemo, useState } from "react";
import { Calendar, Clock, MapPin, Tv, Plus, Pencil, Trash2, X, Save, Radio } from "lucide-react";
import scheduleBackground from "../images/mybackground4.jpg";
import { useNotifications } from "../context/NotificationContext";
import { useAuth } from "../context/AuthContext";

const blank={status:"upcoming",time:"7:30 PM",date:"",venue:"City Dome Arena",broadcast:"League Pass / YouTube",homeTeam:"J-Town Hoops",homeLogo:"/src/images/jtownteamlogo.jpg",homeScore:"",awayTeam:"",awayLogo:"/src/images/jtownteamlogo.jpg",awayScore:"",gameType:"League Game"};
export default function Schedule(){
 const { isAdmin } = useAuth();
 const {scheduleGames,addScheduleGame,updateScheduleGame,removeScheduleGame}=useNotifications(); const [filter,setFilter]=useState("all"); const [showEditor,setShowEditor]=useState(false); const [editingId,setEditingId]=useState(null); const [form,setForm]=useState(blank);
 const matches=useMemo(()=>filter==="all"?scheduleGames:scheduleGames.filter(g=>g.status===filter),[scheduleGames,filter]);
 const openAdd=()=>{setEditingId(null);setForm(blank);setShowEditor(true)}; const openEdit=g=>{setEditingId(g.id);setForm({...g,homeScore:g.homeScore??"",awayScore:g.awayScore??""});setShowEditor(true)};
 const save=e=>{e.preventDefault();if(!form.homeTeam.trim()||!form.awayTeam.trim())return;const payload={...form,homeScore:form.homeScore===""?null:Number(form.homeScore),awayScore:form.awayScore===""?null:Number(form.awayScore)};editingId?updateScheduleGame(editingId,payload):addScheduleGame(payload);setShowEditor(false)};
 const del=g=>{if(window.confirm(`Delete ${g.homeTeam} vs ${g.awayTeam}?`))removeScheduleGame(g.id)};
 return <div className="min-h-screen text-white px-4 sm:px-6 py-10 bg-cover bg-center bg-fixed" style={{backgroundImage:`linear-gradient(rgba(0,0,0,.58),rgba(0,0,0,.64)),url(${scheduleBackground})`}}><div className="max-w-6xl mx-auto">
 <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5 mb-8"><div><p className="text-orange-400 text-xs font-black uppercase tracking-[.35em]">Master Game Calendar</p><h1 className="text-4xl font-black uppercase mt-2 flex gap-3 items-center"><Calendar className="text-orange-500"/> Schedule</h1><p className="text-neutral-400 mt-2">This is the master basketball schedule. Games.jsx reads these same records automatically.</p></div>{isAdmin&&<button onClick={openAdd} className="bg-orange-500 hover:bg-orange-400 text-black font-black px-5 py-3 rounded-xl flex items-center justify-center gap-2"><Plus size={18}/> Add Game</button>}</div>
 <div className="flex flex-wrap gap-2 mb-7">{["all","live","upcoming","completed"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-4 py-2 rounded-full text-xs uppercase font-black ${filter===f?"bg-orange-500 text-black":"bg-black/70 border border-neutral-800 text-neutral-300"}`}>{f}</button>)}</div>
 <div className="space-y-5">{matches.map(g=><article key={g.id} className={`bg-black/75 border rounded-2xl p-5 sm:p-6 ${g.status==="live"?"border-red-500/60 shadow-lg shadow-red-500/10":"border-neutral-800"}`}><div className="flex flex-col xl:flex-row gap-5 xl:items-center"><div className="xl:w-44"><span className={`inline-flex items-center gap-1 text-[10px] font-black uppercase px-2.5 py-1 rounded-full ${g.status==="live"?"bg-red-500/20 text-red-400":g.status==="completed"?"bg-green-500/20 text-green-400":"bg-blue-500/20 text-blue-400"}`}>{g.status==="live"&&<Radio size={11}/>} {g.status}</span><p className="font-black mt-2">{g.date}</p><p className="text-orange-400 text-sm">{g.gameType}</p></div><div className="flex-1 grid grid-cols-[1fr_auto_1fr] gap-4 items-center"><Team logo={g.homeLogo} name={g.homeTeam} label="Home"/><div className="text-center">{g.homeScore!==null&&g.awayScore!==null?<div className="text-3xl font-black font-mono">{g.homeScore}<span className="text-neutral-600 mx-2">:</span>{g.awayScore}</div>:<div className="text-orange-400 font-black">VS</div>}<div className="text-xs text-neutral-400 mt-1 flex justify-center items-center gap-1"><Clock size={12}/>{g.time}</div></div><Team logo={g.awayLogo} name={g.awayTeam} label="Away"/></div><div className="xl:w-64 text-sm text-neutral-400 space-y-2"><p className="flex gap-2"><MapPin size={16} className="text-orange-400"/>{g.venue}</p><p className="flex gap-2"><Tv size={16}/>{g.broadcast}</p></div>{isAdmin&&<div className="flex gap-2"><button onClick={()=>openEdit(g)} className="p-3 bg-orange-500/10 text-orange-400 rounded-xl hover:bg-orange-500 hover:text-black"><Pencil size={17}/></button><button onClick={()=>del(g)} className="p-3 bg-red-500/10 text-red-400 rounded-xl hover:bg-red-500 hover:text-white"><Trash2 size={17}/></button></div>}</div></article>)}{!matches.length&&<div className="border border-dashed border-neutral-700 rounded-2xl p-12 text-center text-neutral-500">No games in this category.</div>}</div>
 </div>
 {showEditor&&isAdmin&&<div className="fixed inset-0 z-[12000] bg-black/85 backdrop-blur-sm p-4 overflow-y-auto"><form onSubmit={save} className="max-w-3xl mx-auto my-8 bg-[#111] border border-neutral-800 rounded-3xl p-6"><div className="flex justify-between mb-5"><div><h2 className="text-2xl font-black">{editingId?"Edit Game":"Add Game"}</h2><p className="text-sm text-neutral-500">Saving here updates Schedule, Games, News and Notifications.</p></div><button type="button" onClick={()=>setShowEditor(false)}><X/></button></div><div className="grid md:grid-cols-2 gap-4"><Field label="Home Team" value={form.homeTeam} set={v=>setForm({...form,homeTeam:v})}/><Field label="Away Team" value={form.awayTeam} set={v=>setForm({...form,awayTeam:v})}/><Field label="Date" value={form.date} set={v=>setForm({...form,date:v})} placeholder="Sat, Sep 26"/><Field label="Time" value={form.time} set={v=>setForm({...form,time:v})}/><Field label="Venue" value={form.venue} set={v=>setForm({...form,venue:v})}/><Field label="Broadcast" value={form.broadcast} set={v=>setForm({...form,broadcast:v})}/><Field label="Game Type" value={form.gameType} set={v=>setForm({...form,gameType:v})}/><label className="text-sm text-neutral-400">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full bg-neutral-950 border border-neutral-800 rounded-xl p-3 text-white"><option value="upcoming">Upcoming</option><option value="live">Live</option><option value="completed">Completed</option></select></label><Field label="Home Score (optional)" type="number" value={form.homeScore} set={v=>setForm({...form,homeScore:v})}/><Field label="Away Score (optional)" type="number" value={form.awayScore} set={v=>setForm({...form,awayScore:v})}/><Field label="Home Logo path" value={form.homeLogo} set={v=>setForm({...form,homeLogo:v})}/><Field label="Away Logo path" value={form.awayLogo} set={v=>setForm({...form,awayLogo:v})}/></div><button className="mt-6 w-full bg-orange-500 hover:bg-orange-400 text-black font-black py-3 rounded-xl flex justify-center gap-2 items-center"><Save size={17}/> Save Game</button></form></div>}
 </div>
}
function Team({logo,name,label}){return <div className="text-center"><img src={logo} alt={name} className="w-14 h-14 rounded-full object-cover mx-auto border border-neutral-700"/><p className="font-black mt-2 text-sm">{name}</p><p className="text-[9px] text-neutral-500 uppercase">{label}</p></div>}
function Field({label,value,set,type="text",placeholder}){return <label className="text-sm text-neutral-400">{label}<input type={type} placeholder={placeholder} value={value??""} onChange={e=>set(e.target.value)} className="mt-1 w-full bg-neutral-950 border border-neutral-800 rounded-xl p-3 text-white outline-none focus:border-orange-500"/></label>}
